"""empty message

Revision ID: 2d598cab46ac
Revises: 
Create Date: 2020-06-01 21:23:03.692738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d598cab46ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('announcedData', sa.DateTime(), nullable=True),
    sa.Column('period', sa.Integer(), nullable=True),
    sa.Column('left_time', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=True),
    sa.Column('gameStarted', sa.Boolean(), nullable=True),
    sa.Column('startData', sa.DateTime(), nullable=True),
    sa.Column('roundEndData', sa.DateTime(), nullable=True),
    sa.Column('secretCode', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_name'), 'game', ['name'], unique=False)
    op.create_index(op.f('ix_game_secretCode'), 'game', ['secretCode'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('terminal_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_name', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('text', sa.String(length=200), nullable=True),
    sa.Column('answer', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['game_name'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_terminal_message_answer'), 'terminal_message', ['answer'], unique=False)
    op.create_index(op.f('ix_terminal_message_author'), 'terminal_message', ['author'], unique=False)
    op.create_index(op.f('ix_terminal_message_text'), 'terminal_message', ['text'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_terminal_message_text'), table_name='terminal_message')
    op.drop_index(op.f('ix_terminal_message_author'), table_name='terminal_message')
    op.drop_index(op.f('ix_terminal_message_answer'), table_name='terminal_message')
    op.drop_table('terminal_message')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_game_secretCode'), table_name='game')
    op.drop_index(op.f('ix_game_name'), table_name='game')
    op.drop_table('game')
    # ### end Alembic commands ###
